# fly.toml app configuration file generated for green-sea-8395 on 2023-08-25T19:01:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-sea-8395"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
